name: EPG Grabber

on:
  schedule:
    - cron: '0 22 * * *' # 22:00 UTC / 03:30 IST
  workflow_dispatch:

jobs:
  epg:
    name: EPG Grabber & Downloader
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Configure Git
      - name: Configure Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions Bot"

      # Step 3: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: package-lock.json

      # Step 4: Install Node.js dependencies
      - name: Install Node.js dependencies
        run: npm install --no-audit --no-fund --legacy-peer-deps

      # Step 5: Grab DishTV EPG
      - name: Grab DishTV EPG
        run: |
          TZ=Asia/Kolkata npm run grab -- --channels=sites/dishtv.in/dishtv.xml --maxConnections=10 --days=2 --gzip
          mkdir -p epg
          cp guide.xml epg/dishtv.xml
          python3 scripts/dishtv_epg.py
          cp guide.xml.gz epg/dishtv.xml.gz

      # Step 6: Grab TataPlay EPG
      - name: Grab TataPlay EPG
        run: |
          TZ=Asia/Kolkata npm run grab -- --channels=sites/tataplay.com/tataplay.xml --maxConnections=10 --days=2 --gzip
          mkdir -p epg
          cp guide.xml epg/tataplay.xml
          python3 scripts/tataplay_epg.py
          cp guide.xml.gz epg/tataplay.xml.gz

      # Step 7: Grab DistroTV EPG
      - name: Grab DistroTV EPG
        run: |
          TZ=Asia/Kolkata npm run grab -- --channels=sites/distrotv.tv/distrotv.xml --maxConnections=10 --days=2 --gzip
          mkdir -p epg
          cp guide.xml epg/distrotv.xml
          python3 scripts/distrotv_epg.py
          cp guide.xml.gz epg/distrotv.xml.gz

      # Step 8: Setup Python for EPG Downloader
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Python dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install requests
          fi

      # Step 9: Run XML Organizer Script
      - name: Run XML Organizer Script
        run: |
          export TZ=Asia/Kolkata
          date
          python scripts/epg-downloader.py

      # Step 10: Get current IST date
      - name: Get current date in IST
        id: get_date
        env:
          TZ: Asia/Kolkata
        run: echo "current_date=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV

      # Step 11: Commit & push only .xml.gz files
      - name: Commit & push updated EPG files
        run: |
          git add epg/*.xml.gz || true
          git commit -m "EPG updated at ${{ env.current_date }} (IST)" || echo "No changes to commit"
          git pull --rebase origin main || true
          git push
